// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protosrv/bacsrv.proto

/*
Package protosrv is a generated protocol buffer package.

It is generated from these files:
	protosrv/bacsrv.proto

It has these top-level messages:
	PingRequest
	PingResponse
	BackupRequest
	BackupResponse
	RestoreRequest
	RestoreWholeBackupDifferentPlaceRequest
	RestoreDirRequest
	RestoreDirRemoteDifferentPlaceRequest
	RestoreResponse
	ListBackupsRequest
	ListBackupsResponse
	ListClientsRequest
	ListClientsResponse
*/
package protosrv

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PingRequest struct {
	Ip string `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"`
}

func (m *PingRequest) Reset()                    { *m = PingRequest{} }
func (m *PingRequest) String() string            { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()               {}
func (*PingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PingRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type PingResponse struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *PingResponse) Reset()                    { *m = PingResponse{} }
func (m *PingResponse) String() string            { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()               {}
func (*PingResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PingResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// From  server
type BackupRequest struct {
	Ip    string   `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"`
	Paths []string `protobuf:"bytes,2,rep,name=paths" json:"paths,omitempty"`
}

func (m *BackupRequest) Reset()                    { *m = BackupRequest{} }
func (m *BackupRequest) String() string            { return proto.CompactTextString(m) }
func (*BackupRequest) ProtoMessage()               {}
func (*BackupRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *BackupRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *BackupRequest) GetPaths() []string {
	if m != nil {
		return m.Paths
	}
	return nil
}

// For Cli
type BackupResponse struct {
	Backupstatus bool `protobuf:"varint,1,opt,name=backupstatus" json:"backupstatus,omitempty"`
}

func (m *BackupResponse) Reset()                    { *m = BackupResponse{} }
func (m *BackupResponse) String() string            { return proto.CompactTextString(m) }
func (*BackupResponse) ProtoMessage()               {}
func (*BackupResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *BackupResponse) GetBackupstatus() bool {
	if m != nil {
		return m.Backupstatus
	}
	return false
}

// Main message must be always
type RestoreRequest struct {
	Ip       string `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"`
	Backupid int64  `protobuf:"varint,2,opt,name=backupid" json:"backupid,omitempty"`
}

func (m *RestoreRequest) Reset()                    { *m = RestoreRequest{} }
func (m *RestoreRequest) String() string            { return proto.CompactTextString(m) }
func (*RestoreRequest) ProtoMessage()               {}
func (*RestoreRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *RestoreRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *RestoreRequest) GetBackupid() int64 {
	if m != nil {
		return m.Backupid
	}
	return 0
}

// Remote path specified of restore
type RestoreWholeBackupDifferentPlaceRequest struct {
	Restorerequest *RestoreRequest `protobuf:"bytes,1,opt,name=restorerequest" json:"restorerequest,omitempty"`
	Remotedir      string          `protobuf:"bytes,2,opt,name=remotedir" json:"remotedir,omitempty"`
}

func (m *RestoreWholeBackupDifferentPlaceRequest) Reset() {
	*m = RestoreWholeBackupDifferentPlaceRequest{}
}
func (m *RestoreWholeBackupDifferentPlaceRequest) String() string { return proto.CompactTextString(m) }
func (*RestoreWholeBackupDifferentPlaceRequest) ProtoMessage()    {}
func (*RestoreWholeBackupDifferentPlaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{5}
}

func (m *RestoreWholeBackupDifferentPlaceRequest) GetRestorerequest() *RestoreRequest {
	if m != nil {
		return m.Restorerequest
	}
	return nil
}

func (m *RestoreWholeBackupDifferentPlaceRequest) GetRemotedir() string {
	if m != nil {
		return m.Remotedir
	}
	return ""
}

// Restoring just file(s) or directory(s) to the same place
type RestoreDirRequest struct {
	Restorerequest *RestoreRequest `protobuf:"bytes,1,opt,name=restorerequest" json:"restorerequest,omitempty"`
	ObjectPaths    []string        `protobuf:"bytes,2,rep,name=objectPaths" json:"objectPaths,omitempty"`
}

func (m *RestoreDirRequest) Reset()                    { *m = RestoreDirRequest{} }
func (m *RestoreDirRequest) String() string            { return proto.CompactTextString(m) }
func (*RestoreDirRequest) ProtoMessage()               {}
func (*RestoreDirRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *RestoreDirRequest) GetRestorerequest() *RestoreRequest {
	if m != nil {
		return m.Restorerequest
	}
	return nil
}

func (m *RestoreDirRequest) GetObjectPaths() []string {
	if m != nil {
		return m.ObjectPaths
	}
	return nil
}

// Restoring file or directory to different remote place
type RestoreDirRemoteDifferentPlaceRequest struct {
	Restorerequest *RestoreRequest `protobuf:"bytes,1,opt,name=restorerequest" json:"restorerequest,omitempty"`
	ObjectsPaths   []string        `protobuf:"bytes,2,rep,name=objectsPaths" json:"objectsPaths,omitempty"`
	Remotedir      string          `protobuf:"bytes,3,opt,name=remotedir" json:"remotedir,omitempty"`
}

func (m *RestoreDirRemoteDifferentPlaceRequest) Reset()         { *m = RestoreDirRemoteDifferentPlaceRequest{} }
func (m *RestoreDirRemoteDifferentPlaceRequest) String() string { return proto.CompactTextString(m) }
func (*RestoreDirRemoteDifferentPlaceRequest) ProtoMessage()    {}
func (*RestoreDirRemoteDifferentPlaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{7}
}

func (m *RestoreDirRemoteDifferentPlaceRequest) GetRestorerequest() *RestoreRequest {
	if m != nil {
		return m.Restorerequest
	}
	return nil
}

func (m *RestoreDirRemoteDifferentPlaceRequest) GetObjectsPaths() []string {
	if m != nil {
		return m.ObjectsPaths
	}
	return nil
}

func (m *RestoreDirRemoteDifferentPlaceRequest) GetRemotedir() string {
	if m != nil {
		return m.Remotedir
	}
	return ""
}

// We just want to know a status
// TODO Consider to put here progress of restore
type RestoreResponse struct {
	Status string `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *RestoreResponse) Reset()                    { *m = RestoreResponse{} }
func (m *RestoreResponse) String() string            { return proto.CompactTextString(m) }
func (*RestoreResponse) ProtoMessage()               {}
func (*RestoreResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *RestoreResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type ListBackupsRequest struct {
	ClientName string `protobuf:"bytes,1,opt,name=clientName" json:"clientName,omitempty"`
}

func (m *ListBackupsRequest) Reset()                    { *m = ListBackupsRequest{} }
func (m *ListBackupsRequest) String() string            { return proto.CompactTextString(m) }
func (*ListBackupsRequest) ProtoMessage()               {}
func (*ListBackupsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *ListBackupsRequest) GetClientName() string {
	if m != nil {
		return m.ClientName
	}
	return ""
}

type ListBackupsResponse struct {
	ClientName string  `protobuf:"bytes,1,opt,name=clientName" json:"clientName,omitempty"`
	BackupID   []int64 `protobuf:"varint,2,rep,packed,name=backupID" json:"backupID,omitempty"`
}

func (m *ListBackupsResponse) Reset()                    { *m = ListBackupsResponse{} }
func (m *ListBackupsResponse) String() string            { return proto.CompactTextString(m) }
func (*ListBackupsResponse) ProtoMessage()               {}
func (*ListBackupsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *ListBackupsResponse) GetClientName() string {
	if m != nil {
		return m.ClientName
	}
	return ""
}

func (m *ListBackupsResponse) GetBackupID() []int64 {
	if m != nil {
		return m.BackupID
	}
	return nil
}

type ListClientsRequest struct {
}

func (m *ListClientsRequest) Reset()                    { *m = ListClientsRequest{} }
func (m *ListClientsRequest) String() string            { return proto.CompactTextString(m) }
func (*ListClientsRequest) ProtoMessage()               {}
func (*ListClientsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type ListClientsResponse struct {
	Clients []string `protobuf:"bytes,1,rep,name=clients" json:"clients,omitempty"`
}

func (m *ListClientsResponse) Reset()                    { *m = ListClientsResponse{} }
func (m *ListClientsResponse) String() string            { return proto.CompactTextString(m) }
func (*ListClientsResponse) ProtoMessage()               {}
func (*ListClientsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *ListClientsResponse) GetClients() []string {
	if m != nil {
		return m.Clients
	}
	return nil
}

func init() {
	proto.RegisterType((*PingRequest)(nil), "protosrv.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "protosrv.PingResponse")
	proto.RegisterType((*BackupRequest)(nil), "protosrv.BackupRequest")
	proto.RegisterType((*BackupResponse)(nil), "protosrv.BackupResponse")
	proto.RegisterType((*RestoreRequest)(nil), "protosrv.RestoreRequest")
	proto.RegisterType((*RestoreWholeBackupDifferentPlaceRequest)(nil), "protosrv.RestoreWholeBackupDifferentPlaceRequest")
	proto.RegisterType((*RestoreDirRequest)(nil), "protosrv.RestoreDirRequest")
	proto.RegisterType((*RestoreDirRemoteDifferentPlaceRequest)(nil), "protosrv.RestoreDirRemoteDifferentPlaceRequest")
	proto.RegisterType((*RestoreResponse)(nil), "protosrv.RestoreResponse")
	proto.RegisterType((*ListBackupsRequest)(nil), "protosrv.ListBackupsRequest")
	proto.RegisterType((*ListBackupsResponse)(nil), "protosrv.ListBackupsResponse")
	proto.RegisterType((*ListClientsRequest)(nil), "protosrv.ListClientsRequest")
	proto.RegisterType((*ListClientsResponse)(nil), "protosrv.ListClientsResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Bacsrv service

type BacsrvClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	Backup(ctx context.Context, in *BackupRequest, opts ...grpc.CallOption) (*BackupResponse, error)
	RestoreWholeBackup(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*RestoreResponse, error)
	RestoreWholeBackupDifferentPlace(ctx context.Context, in *RestoreWholeBackupDifferentPlaceRequest, opts ...grpc.CallOption) (*RestoreResponse, error)
	RestoreDir(ctx context.Context, in *RestoreDirRequest, opts ...grpc.CallOption) (*RestoreResponse, error)
	RestoreDirRemoteDifferentPlace(ctx context.Context, in *RestoreDirRemoteDifferentPlaceRequest, opts ...grpc.CallOption) (*RestoreResponse, error)
	ListBackups(ctx context.Context, in *ListBackupsRequest, opts ...grpc.CallOption) (*ListBackupsResponse, error)
	ListClients(ctx context.Context, in *ListClientsRequest, opts ...grpc.CallOption) (*ListClientsResponse, error)
}

type bacsrvClient struct {
	cc *grpc.ClientConn
}

func NewBacsrvClient(cc *grpc.ClientConn) BacsrvClient {
	return &bacsrvClient{cc}
}

func (c *bacsrvClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := grpc.Invoke(ctx, "/protosrv.Bacsrv/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bacsrvClient) Backup(ctx context.Context, in *BackupRequest, opts ...grpc.CallOption) (*BackupResponse, error) {
	out := new(BackupResponse)
	err := grpc.Invoke(ctx, "/protosrv.Bacsrv/Backup", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bacsrvClient) RestoreWholeBackup(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*RestoreResponse, error) {
	out := new(RestoreResponse)
	err := grpc.Invoke(ctx, "/protosrv.Bacsrv/RestoreWholeBackup", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bacsrvClient) RestoreWholeBackupDifferentPlace(ctx context.Context, in *RestoreWholeBackupDifferentPlaceRequest, opts ...grpc.CallOption) (*RestoreResponse, error) {
	out := new(RestoreResponse)
	err := grpc.Invoke(ctx, "/protosrv.Bacsrv/RestoreWholeBackupDifferentPlace", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bacsrvClient) RestoreDir(ctx context.Context, in *RestoreDirRequest, opts ...grpc.CallOption) (*RestoreResponse, error) {
	out := new(RestoreResponse)
	err := grpc.Invoke(ctx, "/protosrv.Bacsrv/RestoreDir", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bacsrvClient) RestoreDirRemoteDifferentPlace(ctx context.Context, in *RestoreDirRemoteDifferentPlaceRequest, opts ...grpc.CallOption) (*RestoreResponse, error) {
	out := new(RestoreResponse)
	err := grpc.Invoke(ctx, "/protosrv.Bacsrv/RestoreDirRemoteDifferentPlace", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bacsrvClient) ListBackups(ctx context.Context, in *ListBackupsRequest, opts ...grpc.CallOption) (*ListBackupsResponse, error) {
	out := new(ListBackupsResponse)
	err := grpc.Invoke(ctx, "/protosrv.Bacsrv/ListBackups", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bacsrvClient) ListClients(ctx context.Context, in *ListClientsRequest, opts ...grpc.CallOption) (*ListClientsResponse, error) {
	out := new(ListClientsResponse)
	err := grpc.Invoke(ctx, "/protosrv.Bacsrv/ListClients", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Bacsrv service

type BacsrvServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	Backup(context.Context, *BackupRequest) (*BackupResponse, error)
	RestoreWholeBackup(context.Context, *RestoreRequest) (*RestoreResponse, error)
	RestoreWholeBackupDifferentPlace(context.Context, *RestoreWholeBackupDifferentPlaceRequest) (*RestoreResponse, error)
	RestoreDir(context.Context, *RestoreDirRequest) (*RestoreResponse, error)
	RestoreDirRemoteDifferentPlace(context.Context, *RestoreDirRemoteDifferentPlaceRequest) (*RestoreResponse, error)
	ListBackups(context.Context, *ListBackupsRequest) (*ListBackupsResponse, error)
	ListClients(context.Context, *ListClientsRequest) (*ListClientsResponse, error)
}

func RegisterBacsrvServer(s *grpc.Server, srv BacsrvServer) {
	s.RegisterService(&_Bacsrv_serviceDesc, srv)
}

func _Bacsrv_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BacsrvServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protosrv.Bacsrv/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BacsrvServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bacsrv_Backup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BacsrvServer).Backup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protosrv.Bacsrv/Backup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BacsrvServer).Backup(ctx, req.(*BackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bacsrv_RestoreWholeBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BacsrvServer).RestoreWholeBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protosrv.Bacsrv/RestoreWholeBackup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BacsrvServer).RestoreWholeBackup(ctx, req.(*RestoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bacsrv_RestoreWholeBackupDifferentPlace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreWholeBackupDifferentPlaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BacsrvServer).RestoreWholeBackupDifferentPlace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protosrv.Bacsrv/RestoreWholeBackupDifferentPlace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BacsrvServer).RestoreWholeBackupDifferentPlace(ctx, req.(*RestoreWholeBackupDifferentPlaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bacsrv_RestoreDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreDirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BacsrvServer).RestoreDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protosrv.Bacsrv/RestoreDir",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BacsrvServer).RestoreDir(ctx, req.(*RestoreDirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bacsrv_RestoreDirRemoteDifferentPlace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreDirRemoteDifferentPlaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BacsrvServer).RestoreDirRemoteDifferentPlace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protosrv.Bacsrv/RestoreDirRemoteDifferentPlace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BacsrvServer).RestoreDirRemoteDifferentPlace(ctx, req.(*RestoreDirRemoteDifferentPlaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bacsrv_ListBackups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBackupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BacsrvServer).ListBackups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protosrv.Bacsrv/ListBackups",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BacsrvServer).ListBackups(ctx, req.(*ListBackupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bacsrv_ListClients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListClientsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BacsrvServer).ListClients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protosrv.Bacsrv/ListClients",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BacsrvServer).ListClients(ctx, req.(*ListClientsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Bacsrv_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protosrv.Bacsrv",
	HandlerType: (*BacsrvServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Bacsrv_Ping_Handler,
		},
		{
			MethodName: "Backup",
			Handler:    _Bacsrv_Backup_Handler,
		},
		{
			MethodName: "RestoreWholeBackup",
			Handler:    _Bacsrv_RestoreWholeBackup_Handler,
		},
		{
			MethodName: "RestoreWholeBackupDifferentPlace",
			Handler:    _Bacsrv_RestoreWholeBackupDifferentPlace_Handler,
		},
		{
			MethodName: "RestoreDir",
			Handler:    _Bacsrv_RestoreDir_Handler,
		},
		{
			MethodName: "RestoreDirRemoteDifferentPlace",
			Handler:    _Bacsrv_RestoreDirRemoteDifferentPlace_Handler,
		},
		{
			MethodName: "ListBackups",
			Handler:    _Bacsrv_ListBackups_Handler,
		},
		{
			MethodName: "ListClients",
			Handler:    _Bacsrv_ListClients_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protosrv/bacsrv.proto",
}

func init() { proto.RegisterFile("protosrv/bacsrv.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 525 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xad, 0x13, 0x1a, 0xe2, 0x49, 0x08, 0x62, 0x69, 0x8b, 0x31, 0x6d, 0x65, 0x8d, 0x84, 0x08,
	0x97, 0x44, 0x94, 0x22, 0x2e, 0x20, 0xa1, 0x12, 0x21, 0x55, 0x54, 0x28, 0xec, 0x85, 0xb3, 0xe3,
	0x6e, 0xdb, 0xa5, 0x89, 0x6d, 0x76, 0x37, 0xe5, 0x37, 0xf0, 0x03, 0xf8, 0x15, 0xfc, 0x49, 0x94,
	0x5d, 0x7f, 0x3b, 0x4e, 0x2e, 0x70, 0x9c, 0xb7, 0x33, 0xef, 0x8d, 0xc7, 0xef, 0xc1, 0x7e, 0x2c,
	0x22, 0x15, 0x49, 0x71, 0x37, 0x9e, 0xf9, 0x81, 0x14, 0x77, 0x23, 0x5d, 0x93, 0x6e, 0x0a, 0xe3,
	0x11, 0xf4, 0xa6, 0x3c, 0xbc, 0xa6, 0xec, 0xc7, 0x92, 0x49, 0x45, 0x06, 0xd0, 0xe2, 0xb1, 0x63,
	0x79, 0xd6, 0xd0, 0xa6, 0x2d, 0x1e, 0xe3, 0x10, 0xfa, 0xe6, 0x59, 0xc6, 0x51, 0x28, 0x19, 0x71,
	0xe0, 0xfe, 0x82, 0x49, 0xe9, 0x5f, 0xb3, 0xa4, 0x29, 0x2d, 0xf1, 0x0d, 0x3c, 0x38, 0xf3, 0x83,
	0xdb, 0x65, 0xdc, 0x40, 0x45, 0xf6, 0x60, 0x37, 0xf6, 0xd5, 0x8d, 0x74, 0x5a, 0x5e, 0x7b, 0x68,
	0x53, 0x53, 0xe0, 0x29, 0x0c, 0xd2, 0xb1, 0x44, 0x02, 0xa1, 0x3f, 0xd3, 0x88, 0x54, 0xbe, 0x5a,
	0x4a, 0xcd, 0xd0, 0xa5, 0x25, 0x0c, 0xdf, 0xc1, 0x80, 0x32, 0xa9, 0x22, 0xc1, 0x9a, 0xd4, 0x5c,
	0xe8, 0x9a, 0x09, 0x7e, 0xe9, 0xb4, 0x3c, 0x6b, 0xd8, 0xa6, 0x59, 0x8d, 0xbf, 0x2c, 0x78, 0x91,
	0x8c, 0x7f, 0xbb, 0x89, 0xe6, 0xcc, 0x2c, 0x30, 0xe1, 0x57, 0x57, 0x4c, 0xb0, 0x50, 0x4d, 0xe7,
	0x7e, 0x90, 0xf1, 0x7e, 0x80, 0x81, 0x30, 0xad, 0xc2, 0x20, 0x5a, 0xa3, 0x77, 0xe2, 0x8c, 0xd2,
	0x13, 0x8e, 0xca, 0x9b, 0xd0, 0x4a, 0x3f, 0x39, 0x04, 0x5b, 0xb0, 0x45, 0xa4, 0xd8, 0x25, 0x17,
	0x7a, 0x15, 0x9b, 0xe6, 0x00, 0xfe, 0x84, 0x47, 0xc9, 0xfc, 0x84, 0x8b, 0x7f, 0x27, 0xea, 0x41,
	0x2f, 0x9a, 0x7d, 0x67, 0x81, 0x9a, 0x16, 0x4e, 0x5e, 0x84, 0xf0, 0x8f, 0x05, 0xcf, 0x8b, 0xca,
	0xab, 0x85, 0xfe, 0xd7, 0x09, 0x10, 0xfa, 0x46, 0x5a, 0x16, 0xd7, 0x29, 0x61, 0xe5, 0x33, 0xb5,
	0xab, 0x67, 0x7a, 0x09, 0x0f, 0x33, 0x8d, 0xc4, 0x27, 0x07, 0xd0, 0x29, 0x38, 0xc4, 0xa6, 0x49,
	0x85, 0xa7, 0x40, 0x2e, 0xb8, 0x54, 0xe6, 0xa7, 0xca, 0xf4, 0x23, 0x8e, 0x01, 0x82, 0x39, 0x67,
	0xa1, 0xfa, 0xe2, 0x2f, 0x52, 0xef, 0x16, 0x10, 0xfc, 0x0a, 0x8f, 0x4b, 0x53, 0x89, 0xc8, 0x96,
	0xb1, 0xdc, 0x66, 0xe7, 0x13, 0xfd, 0x55, 0x99, 0xcd, 0xce, 0x27, 0xb8, 0x67, 0x16, 0xf9, 0xa8,
	0xbb, 0xd3, 0x45, 0x70, 0x6c, 0x84, 0x32, 0x34, 0x0f, 0x96, 0xa1, 0x5d, 0x7d, 0xce, 0xea, 0x3a,
	0x69, 0x79, 0xf2, 0x7b, 0x17, 0x3a, 0x67, 0x3a, 0xbc, 0xe4, 0x2d, 0xdc, 0x5b, 0xa5, 0x91, 0xec,
	0xe7, 0x97, 0x2f, 0x84, 0xd7, 0x3d, 0xa8, 0xc2, 0x86, 0x1b, 0x77, 0xc8, 0x7b, 0x4d, 0x71, 0xbb,
	0x8c, 0xc9, 0x93, 0xbc, 0xa7, 0x14, 0x57, 0xd7, 0xa9, 0x3f, 0x64, 0xe3, 0x9f, 0x81, 0xd4, 0xf3,
	0x42, 0x1a, 0xff, 0xbf, 0xfb, 0x74, 0xcd, 0x4b, 0x46, 0x26, 0xc0, 0xdb, 0x16, 0x3e, 0xf2, 0xaa,
	0x46, 0xb0, 0x2d, 0xa8, 0x9b, 0x35, 0x3f, 0x01, 0xe4, 0x5e, 0x27, 0xcf, 0x6a, 0xad, 0x79, 0xf6,
	0x36, 0xf3, 0x84, 0x70, 0xbc, 0x39, 0x33, 0x64, 0xbc, 0x9e, 0xbb, 0x31, 0x5d, 0x9b, 0xf5, 0x2e,
	0xa0, 0x57, 0x70, 0x25, 0x39, 0xcc, 0x7b, 0xeb, 0x16, 0x77, 0x8f, 0x1a, 0x5e, 0xab, 0x6c, 0x89,
	0xf5, 0xaa, 0x6c, 0x65, 0x9f, 0x56, 0xd9, 0x2a, 0x7e, 0xc5, 0x9d, 0x59, 0x47, 0xbf, 0xbf, 0xfe,
	0x1b, 0x00, 0x00, 0xff, 0xff, 0x6c, 0x02, 0x80, 0xd5, 0x63, 0x06, 0x00, 0x00,
}
