// Code generated by protoc-gen-go.
// source: server.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	server.proto

It has these top-level messages:
	Paths
	Status
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the user's name.
type Paths struct {
	Path string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
}

func (m *Paths) Reset()                    { *m = Paths{} }
func (m *Paths) String() string            { return proto1.CompactTextString(m) }
func (*Paths) ProtoMessage()               {}
func (*Paths) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// The response message containing the greetings
type Status struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *Status) Reset()                    { *m = Status{} }
func (m *Status) String() string            { return proto1.CompactTextString(m) }
func (*Status) ProtoMessage()               {}
func (*Status) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto1.RegisterType((*Paths)(nil), "proto.Paths")
	proto1.RegisterType((*Status)(nil), "proto.Status")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Baclnt service

type BaclntClient interface {
	TriggerBackup(ctx context.Context, opts ...grpc.CallOption) (Baclnt_TriggerBackupClient, error)
}

type baclntClient struct {
	cc *grpc.ClientConn
}

func NewBaclntClient(cc *grpc.ClientConn) BaclntClient {
	return &baclntClient{cc}
}

func (c *baclntClient) TriggerBackup(ctx context.Context, opts ...grpc.CallOption) (Baclnt_TriggerBackupClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Baclnt_serviceDesc.Streams[0], c.cc, "/proto.Baclnt/TriggerBackup", opts...)
	if err != nil {
		return nil, err
	}
	x := &baclntTriggerBackupClient{stream}
	return x, nil
}

type Baclnt_TriggerBackupClient interface {
	Send(*Paths) error
	CloseAndRecv() (*Status, error)
	grpc.ClientStream
}

type baclntTriggerBackupClient struct {
	grpc.ClientStream
}

func (x *baclntTriggerBackupClient) Send(m *Paths) error {
	return x.ClientStream.SendMsg(m)
}

func (x *baclntTriggerBackupClient) CloseAndRecv() (*Status, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Status)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Baclnt service

type BaclntServer interface {
	TriggerBackup(Baclnt_TriggerBackupServer) error
}

func RegisterBaclntServer(s *grpc.Server, srv BaclntServer) {
	s.RegisterService(&_Baclnt_serviceDesc, srv)
}

func _Baclnt_TriggerBackup_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BaclntServer).TriggerBackup(&baclntTriggerBackupServer{stream})
}

type Baclnt_TriggerBackupServer interface {
	SendAndClose(*Status) error
	Recv() (*Paths, error)
	grpc.ServerStream
}

type baclntTriggerBackupServer struct {
	grpc.ServerStream
}

func (x *baclntTriggerBackupServer) SendAndClose(m *Status) error {
	return x.ServerStream.SendMsg(m)
}

func (x *baclntTriggerBackupServer) Recv() (*Paths, error) {
	m := new(Paths)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Baclnt_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Baclnt",
	HandlerType: (*BaclntServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TriggerBackup",
			Handler:       _Baclnt_TriggerBackup_Handler,
			ClientStreams: true,
		},
	},
	Metadata: fileDescriptor0,
}

func init() { proto1.RegisterFile("server.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 139 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x4e, 0x2d, 0x2a,
	0x4b, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0xd2, 0x5c, 0xac,
	0x01, 0x89, 0x25, 0x19, 0xc5, 0x42, 0x42, 0x5c, 0x2c, 0x05, 0x40, 0x86, 0x04, 0xa3, 0x02, 0xa3,
	0x06, 0x67, 0x10, 0x98, 0xad, 0xa4, 0xc4, 0xc5, 0x16, 0x5c, 0x92, 0x58, 0x52, 0x5a, 0x2c, 0x24,
	0xc1, 0xc5, 0x9e, 0x9b, 0x5a, 0x5c, 0x9c, 0x98, 0x9e, 0x0a, 0x55, 0x00, 0xe3, 0x1a, 0x59, 0x71,
	0xb1, 0x39, 0x25, 0x26, 0xe7, 0xe4, 0x95, 0x08, 0x19, 0x70, 0xf1, 0x86, 0x14, 0x65, 0xa6, 0xa7,
	0xa7, 0x16, 0x01, 0x05, 0xb2, 0x4b, 0x0b, 0x84, 0x78, 0x20, 0x56, 0xe9, 0x81, 0x2d, 0x90, 0xe2,
	0x85, 0xf2, 0x20, 0x26, 0x2a, 0x31, 0x68, 0x30, 0x26, 0xb1, 0x81, 0x45, 0x8c, 0x01, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xfa, 0xa6, 0xbc, 0xf0, 0x9a, 0x00, 0x00, 0x00,
}
