// Code generated by protoc-gen-go.
// source: server.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	server.proto

It has these top-level messages:
	Paths
	Status
	Info
*/
package proto

import proto1 "github.com/golang/protobuf/proto"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal

// The request message containing the user's name.
type Paths struct {
	Path string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
}

func (m *Paths) Reset()         { *m = Paths{} }
func (m *Paths) String() string { return proto1.CompactTextString(m) }
func (*Paths) ProtoMessage()    {}

// The response message containing the greetings
type Status struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto1.CompactTextString(m) }
func (*Status) ProtoMessage()    {}

type Info struct {
	Path   string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	Size   int64  `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
	Exists bool   `protobuf:"varint,3,opt,name=exists" json:"exists,omitempty"`
}

func (m *Info) Reset()         { *m = Info{} }
func (m *Info) String() string { return proto1.CompactTextString(m) }
func (*Info) ProtoMessage()    {}

func init() {
}

// Client API for Baclnt service

type BaclntClient interface {
	TriggerBackup(ctx context.Context, opts ...grpc.CallOption) (Baclnt_TriggerBackupClient, error)
	GetStatusPaths(ctx context.Context, opts ...grpc.CallOption) (Baclnt_GetStatusPathsClient, error)
}

type baclntClient struct {
	cc *grpc.ClientConn
}

func NewBaclntClient(cc *grpc.ClientConn) BaclntClient {
	return &baclntClient{cc}
}

func (c *baclntClient) TriggerBackup(ctx context.Context, opts ...grpc.CallOption) (Baclnt_TriggerBackupClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Baclnt_serviceDesc.Streams[0], c.cc, "/proto.Baclnt/TriggerBackup", opts...)
	if err != nil {
		return nil, err
	}
	x := &baclntTriggerBackupClient{stream}
	return x, nil
}

type Baclnt_TriggerBackupClient interface {
	Send(*Paths) error
	CloseAndRecv() (*Status, error)
	grpc.ClientStream
}

type baclntTriggerBackupClient struct {
	grpc.ClientStream
}

func (x *baclntTriggerBackupClient) Send(m *Paths) error {
	return x.ClientStream.SendMsg(m)
}

func (x *baclntTriggerBackupClient) CloseAndRecv() (*Status, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Status)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *baclntClient) GetStatusPaths(ctx context.Context, opts ...grpc.CallOption) (Baclnt_GetStatusPathsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Baclnt_serviceDesc.Streams[1], c.cc, "/proto.Baclnt/GetStatusPaths", opts...)
	if err != nil {
		return nil, err
	}
	x := &baclntGetStatusPathsClient{stream}
	return x, nil
}

type Baclnt_GetStatusPathsClient interface {
	Send(*Paths) error
	Recv() (*Info, error)
	grpc.ClientStream
}

type baclntGetStatusPathsClient struct {
	grpc.ClientStream
}

func (x *baclntGetStatusPathsClient) Send(m *Paths) error {
	return x.ClientStream.SendMsg(m)
}

func (x *baclntGetStatusPathsClient) Recv() (*Info, error) {
	m := new(Info)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Baclnt service

type BaclntServer interface {
	TriggerBackup(Baclnt_TriggerBackupServer) error
	GetStatusPaths(Baclnt_GetStatusPathsServer) error
}

func RegisterBaclntServer(s *grpc.Server, srv BaclntServer) {
	s.RegisterService(&_Baclnt_serviceDesc, srv)
}

func _Baclnt_TriggerBackup_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BaclntServer).TriggerBackup(&baclntTriggerBackupServer{stream})
}

type Baclnt_TriggerBackupServer interface {
	SendAndClose(*Status) error
	Recv() (*Paths, error)
	grpc.ServerStream
}

type baclntTriggerBackupServer struct {
	grpc.ServerStream
}

func (x *baclntTriggerBackupServer) SendAndClose(m *Status) error {
	return x.ServerStream.SendMsg(m)
}

func (x *baclntTriggerBackupServer) Recv() (*Paths, error) {
	m := new(Paths)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Baclnt_GetStatusPaths_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BaclntServer).GetStatusPaths(&baclntGetStatusPathsServer{stream})
}

type Baclnt_GetStatusPathsServer interface {
	Send(*Info) error
	Recv() (*Paths, error)
	grpc.ServerStream
}

type baclntGetStatusPathsServer struct {
	grpc.ServerStream
}

func (x *baclntGetStatusPathsServer) Send(m *Info) error {
	return x.ServerStream.SendMsg(m)
}

func (x *baclntGetStatusPathsServer) Recv() (*Paths, error) {
	m := new(Paths)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Baclnt_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Baclnt",
	HandlerType: (*BaclntServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TriggerBackup",
			Handler:       _Baclnt_TriggerBackup_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GetStatusPaths",
			Handler:       _Baclnt_GetStatusPaths_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
}
