// Code generated by protoc-gen-go.
// source: server.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	server.proto

It has these top-level messages:
	HelloRequest
	HelloReply
	Paths
	Status
	Info
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the user's name.
type HelloRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *HelloRequest) Reset()                    { *m = HelloRequest{} }
func (m *HelloRequest) String() string            { return proto1.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()               {}
func (*HelloRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message containing the greetings
type HelloReply struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *HelloReply) Reset()                    { *m = HelloReply{} }
func (m *HelloReply) String() string            { return proto1.CompactTextString(m) }
func (*HelloReply) ProtoMessage()               {}
func (*HelloReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// The request message containing the user's name.
type Paths struct {
	Path string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
}

func (m *Paths) Reset()                    { *m = Paths{} }
func (m *Paths) String() string            { return proto1.CompactTextString(m) }
func (*Paths) ProtoMessage()               {}
func (*Paths) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Paths) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

// The response message containing the greetings
type Status struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *Status) Reset()                    { *m = Status{} }
func (m *Status) String() string            { return proto1.CompactTextString(m) }
func (*Status) ProtoMessage()               {}
func (*Status) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Info struct {
	Path   string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	Size   int64  `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
	Exists bool   `protobuf:"varint,3,opt,name=exists" json:"exists,omitempty"`
}

func (m *Info) Reset()                    { *m = Info{} }
func (m *Info) String() string            { return proto1.CompactTextString(m) }
func (*Info) ProtoMessage()               {}
func (*Info) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Info) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Info) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Info) GetExists() bool {
	if m != nil {
		return m.Exists
	}
	return false
}

func init() {
	proto1.RegisterType((*HelloRequest)(nil), "proto.HelloRequest")
	proto1.RegisterType((*HelloReply)(nil), "proto.HelloReply")
	proto1.RegisterType((*Paths)(nil), "proto.Paths")
	proto1.RegisterType((*Status)(nil), "proto.Status")
	proto1.RegisterType((*Info)(nil), "proto.Info")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Baclnt service

type BaclntClient interface {
	TriggerBackup(ctx context.Context, opts ...grpc.CallOption) (Baclnt_TriggerBackupClient, error)
	GetStatusPaths(ctx context.Context, opts ...grpc.CallOption) (Baclnt_GetStatusPathsClient, error)
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type baclntClient struct {
	cc *grpc.ClientConn
}

func NewBaclntClient(cc *grpc.ClientConn) BaclntClient {
	return &baclntClient{cc}
}

func (c *baclntClient) TriggerBackup(ctx context.Context, opts ...grpc.CallOption) (Baclnt_TriggerBackupClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Baclnt_serviceDesc.Streams[0], c.cc, "/proto.Baclnt/TriggerBackup", opts...)
	if err != nil {
		return nil, err
	}
	x := &baclntTriggerBackupClient{stream}
	return x, nil
}

type Baclnt_TriggerBackupClient interface {
	Send(*Paths) error
	CloseAndRecv() (*Status, error)
	grpc.ClientStream
}

type baclntTriggerBackupClient struct {
	grpc.ClientStream
}

func (x *baclntTriggerBackupClient) Send(m *Paths) error {
	return x.ClientStream.SendMsg(m)
}

func (x *baclntTriggerBackupClient) CloseAndRecv() (*Status, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Status)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *baclntClient) GetStatusPaths(ctx context.Context, opts ...grpc.CallOption) (Baclnt_GetStatusPathsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Baclnt_serviceDesc.Streams[1], c.cc, "/proto.Baclnt/GetStatusPaths", opts...)
	if err != nil {
		return nil, err
	}
	x := &baclntGetStatusPathsClient{stream}
	return x, nil
}

type Baclnt_GetStatusPathsClient interface {
	Send(*Paths) error
	Recv() (*Info, error)
	grpc.ClientStream
}

type baclntGetStatusPathsClient struct {
	grpc.ClientStream
}

func (x *baclntGetStatusPathsClient) Send(m *Paths) error {
	return x.ClientStream.SendMsg(m)
}

func (x *baclntGetStatusPathsClient) Recv() (*Info, error) {
	m := new(Info)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *baclntClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := grpc.Invoke(ctx, "/proto.Baclnt/SayHello", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Baclnt service

type BaclntServer interface {
	TriggerBackup(Baclnt_TriggerBackupServer) error
	GetStatusPaths(Baclnt_GetStatusPathsServer) error
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
}

func RegisterBaclntServer(s *grpc.Server, srv BaclntServer) {
	s.RegisterService(&_Baclnt_serviceDesc, srv)
}

func _Baclnt_TriggerBackup_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BaclntServer).TriggerBackup(&baclntTriggerBackupServer{stream})
}

type Baclnt_TriggerBackupServer interface {
	SendAndClose(*Status) error
	Recv() (*Paths, error)
	grpc.ServerStream
}

type baclntTriggerBackupServer struct {
	grpc.ServerStream
}

func (x *baclntTriggerBackupServer) SendAndClose(m *Status) error {
	return x.ServerStream.SendMsg(m)
}

func (x *baclntTriggerBackupServer) Recv() (*Paths, error) {
	m := new(Paths)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Baclnt_GetStatusPaths_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BaclntServer).GetStatusPaths(&baclntGetStatusPathsServer{stream})
}

type Baclnt_GetStatusPathsServer interface {
	Send(*Info) error
	Recv() (*Paths, error)
	grpc.ServerStream
}

type baclntGetStatusPathsServer struct {
	grpc.ServerStream
}

func (x *baclntGetStatusPathsServer) Send(m *Info) error {
	return x.ServerStream.SendMsg(m)
}

func (x *baclntGetStatusPathsServer) Recv() (*Paths, error) {
	m := new(Paths)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Baclnt_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaclntServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Baclnt/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaclntServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Baclnt_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Baclnt",
	HandlerType: (*BaclntServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Baclnt_SayHello_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TriggerBackup",
			Handler:       _Baclnt_TriggerBackup_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GetStatusPaths",
			Handler:       _Baclnt_GetStatusPaths_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "server.proto",
}

func init() { proto1.RegisterFile("server.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 262 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x50, 0xcb, 0x4e, 0xc3, 0x30,
	0x10, 0xac, 0x69, 0x1b, 0xca, 0x92, 0x22, 0xb1, 0x48, 0x28, 0x2a, 0x97, 0xc8, 0x07, 0x94, 0x53,
	0x55, 0x1e, 0x5f, 0xd0, 0x03, 0x8f, 0x1b, 0x4a, 0xf9, 0x01, 0x53, 0x2d, 0x69, 0x84, 0x9b, 0x18,
	0xdb, 0x41, 0x84, 0xdf, 0xe1, 0x47, 0x91, 0x1d, 0x47, 0x22, 0x12, 0xe2, 0xe4, 0x99, 0xf1, 0xce,
	0x68, 0x76, 0x21, 0x36, 0xa4, 0x3f, 0x48, 0x2f, 0x95, 0xae, 0x6d, 0x8d, 0x53, 0xff, 0x70, 0x0e,
	0xf1, 0x03, 0x49, 0x59, 0xe7, 0xf4, 0xde, 0x90, 0xb1, 0x88, 0x30, 0xa9, 0xc4, 0x9e, 0x12, 0x96,
	0xb2, 0xec, 0x28, 0xf7, 0x98, 0x5f, 0x02, 0x84, 0x19, 0x25, 0x5b, 0x4c, 0xe0, 0x70, 0x4f, 0xc6,
	0x88, 0xa2, 0x1f, 0xea, 0x29, 0xbf, 0x80, 0xe9, 0x93, 0xb0, 0x3b, 0xe3, 0x42, 0x94, 0xb0, 0xbb,
	0x3e, 0xc4, 0x61, 0xce, 0x21, 0xda, 0x58, 0x61, 0x1b, 0xf3, 0x4f, 0xc0, 0x1d, 0x4c, 0x1e, 0xab,
	0xd7, 0xfa, 0x2f, 0xbf, 0xd3, 0x4c, 0xf9, 0x45, 0xc9, 0x41, 0xca, 0xb2, 0x71, 0xee, 0x31, 0x9e,
	0x43, 0x44, 0x9f, 0xa5, 0xb1, 0x26, 0x19, 0xa7, 0x2c, 0x9b, 0xe5, 0x81, 0x5d, 0x7f, 0x33, 0x88,
	0xd6, 0x62, 0x2b, 0x2b, 0x8b, 0x2b, 0x98, 0x3f, 0xeb, 0xb2, 0x28, 0x48, 0xaf, 0xc5, 0xf6, 0xad,
	0x51, 0x18, 0x77, 0xfb, 0x2f, 0x7d, 0xd3, 0xc5, 0x3c, 0xb0, 0xae, 0x1a, 0x1f, 0x65, 0x0c, 0xaf,
	0xe0, 0xe4, 0x9e, 0x6c, 0x27, 0x74, 0xeb, 0x0c, 0x2d, 0xc7, 0x81, 0xb9, 0xa6, 0xce, 0xb0, 0x62,
	0x78, 0x0b, 0xb3, 0x8d, 0x68, 0xfd, 0x8d, 0xf0, 0x2c, 0x7c, 0xff, 0xbe, 0xea, 0xe2, 0x74, 0x28,
	0x2a, 0xd9, 0xf2, 0xd1, 0x4b, 0xe4, 0xb5, 0x9b, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8f, 0x29,
	0xb0, 0xe1, 0x98, 0x01, 0x00, 0x00,
}
