[main]
LogOutput = "STDOUT"
Debug = true
TempDir = "/tmp/backer"
ExternalName = "127.0.0.1" # External name of client, can be hosts/ip/DNS
DataTransferInterface = "127.0.0.1" # IP addres on which data server will listen