[server]
MgmtPort = 9000
DataPort = 8000
LogOutput = "STDOUT"
Debug = true

[repository]
Localization = "/home/damekr/repository"

[clients]
ConfigFile = "/mnt/c/Users/Damian Rajca/dev/go/src/github.com/damekr/backer/config/clients"
