[server]
MgmtPort = 9000
DataPort = 8000
LogOutput = "STDOUT"
Debug = true

[repository]
Localization = "/home/damekr/repository"

[clients]
ConfigFile = "/home/damian/dev/go/src/github.com/backer/clients/clients.toml"
