[main]
DataPort = 9000
ManagementPort = 9090
LogOutput = "STDOUT"
Debug = true
ExternalName = "localhost" # External name of client, can be hosts/ip/DNS
DataTransferInterface = "127.0.0.1" # IP addres on which data server will listen

[server]
ExternalName = "127.0.0.1" # External name of server to allow integration of this client
DataPort = 8000
ManagementPort = 8090