// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protosrv/bacsrv.proto

/*
Package protosrv is a generated protocol buffer package.

It is generated from these files:
	protosrv/bacsrv.proto

It has these top-level messages:
	PingRequest
	PingResponse
*/
package protosrv

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PingRequest struct {
	Ip string `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"`
}

func (m *PingRequest) Reset()                    { *m = PingRequest{} }
func (m *PingRequest) String() string            { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()               {}
func (*PingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PingRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type PingResponse struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *PingResponse) Reset()                    { *m = PingResponse{} }
func (m *PingResponse) String() string            { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()               {}
func (*PingResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PingResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*PingRequest)(nil), "protosrv.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "protosrv.PingResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Bacsrv service

type BacsrvClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type bacsrvClient struct {
	cc *grpc.ClientConn
}

func NewBacsrvClient(cc *grpc.ClientConn) BacsrvClient {
	return &bacsrvClient{cc}
}

func (c *bacsrvClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := grpc.Invoke(ctx, "/protosrv.Bacsrv/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Bacsrv service

type BacsrvServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
}

func RegisterBacsrvServer(s *grpc.Server, srv BacsrvServer) {
	s.RegisterService(&_Bacsrv_serviceDesc, srv)
}

func _Bacsrv_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BacsrvServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protosrv.Bacsrv/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BacsrvServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Bacsrv_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protosrv.Bacsrv",
	HandlerType: (*BacsrvServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Bacsrv_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protosrv/bacsrv.proto",
}

func init() { proto.RegisterFile("protosrv/bacsrv.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 140 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0x28, 0xca, 0x2f,
	0xc9, 0x2f, 0x2e, 0x2a, 0xd3, 0x4f, 0x4a, 0x4c, 0x2e, 0x2e, 0x2a, 0xd3, 0x03, 0xf3, 0x85, 0x38,
	0x60, 0xc2, 0x4a, 0xb2, 0x5c, 0xdc, 0x01, 0x99, 0x79, 0xe9, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5,
	0x25, 0x42, 0x7c, 0x5c, 0x4c, 0x99, 0x05, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x4c, 0x99,
	0x05, 0x4a, 0x1a, 0x5c, 0x3c, 0x10, 0xe9, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x09, 0x2e,
	0xf6, 0xdc, 0xd4, 0xe2, 0xe2, 0xc4, 0xf4, 0x54, 0xa8, 0x22, 0x18, 0xd7, 0xc8, 0x91, 0x8b, 0xcd,
	0x09, 0x6c, 0x85, 0x90, 0x39, 0x17, 0x0b, 0x48, 0x8f, 0x90, 0xa8, 0x1e, 0xcc, 0x16, 0x3d, 0x24,
	0x2b, 0xa4, 0xc4, 0xd0, 0x85, 0x21, 0x46, 0x2b, 0x31, 0x24, 0xb1, 0x81, 0x25, 0x8c, 0x01, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xa7, 0x19, 0xc7, 0x5f, 0xb5, 0x00, 0x00, 0x00,
}
