[hourly]
ID = 1
Description = "Example hourly schedule"

[daily]
ID = 2
Description = "Example daily schedule"
Run = 07:32:00

[weakly]
ID = 3
Description  = "Example weakly schedule"
Run = "07:32:00-mon"