[hourly]
ID = 1
Description = "Example hourly schedule"
Hour = 07:00:00

[daily]
ID = 2
Description = "Example daily schedule"
Hour = 07:32:00

[weakly]
ID = 3
Description  = "Example weakly schedule"
Hour = 07:32:00
Day = "monday"